
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Nabla } from 'next/font/google'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'


const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed w-full h-12 top-0">
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
